services:
  - type: web
    name: myk9q-react
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /sw-custom.js
        name: Service-Worker-Allowed
        value: /
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
